config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}
  root to: 'home#index'
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'register', to: 'devise/registrations#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_one_attached :avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum state: { offline: 0, online: 1 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.where.not(id: current_user.id) if user_signed_in?
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private

    def sign_up_params
        params.require(:user).permit(:name, :email, :avatar, :github_link, :password)
    end

    def account_update_params
        params.require(:user).permit(:name, :email, :github_link, :avatar, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

def developers
    if user_signed_in?
        'home/partials/developers'
    else 
        'home/partials/empty'
    end

end

def links
    if user_signed_in?
        'home/partials/nav/dropdown'
    else
        'home/partials/nav/auth_links'
    end
end


def change_state_btn
    current_user.online? ? "home/partials/nav/dropdown/ gofflinebtn" :
    "home/partials/nav/dropdown/gonlinebtn"
end

def btnStart
    if user_signed_in?
        "home/partials/startbtn/scrollbtn"
    else
        "home/partials/startbtn/authbtn"
    end
end

end

app/views/home/index.html.erb
<%= render 'home/partials/nav' %>
<%= render 'home/partials/header' %>
<%= render developers %>

app/views/home/partials/_developers.html.erb
<section class="developers text-center" id="js-developers">
    <h2 class=title>No appointment needed. Just chat!</h2>
    <div class="container">
        <div class="row my-5">
            <% @users.each do |user| %>
            <div class="col-md-3 col-xs-6">
                <%= render 'home/partials/user-card', user: user %>
            </div>
            <% end %>
        </div>
    </div>
</section>

app/views/home/partials/_header.html.erb
<div class="jumbotron jumbotron-fluid mb-0">
    <div class="container">
        <div class="update">
            <p class="py-1 px-2"><span class="soon mx-2 p-1">SOON</span>TextChat:
                Instant text messaging coming out soon <i class="fas fa-chevronright"></ i>
            </p>
        </div>
        <h1 class="display-4 text-white">The right way to chat with developers,
            globally</h1>
        <p class="lead mb-5">Have an idea to share? Need help with a coding
            challenge? Come chat with your fellow developers. Do it automatically and
            around the globe with DevTime. No appointment needed!
        </p>
        <div class="buttons">
            <%= render btnStart %>
            <a class="btn btn-primary disabled" href="#">TextChat coming soon!!!
            </a>
        </div>
    </div>
</div>
<div class="text-right">
    <%
=begin%>
    <img class="header-image d-none d-md-block mt-3" src="<%=
image_path('Workathome.png') %>" alt="">
    <%
=end%>
</div>

app/views/home/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#"><i class="fas fa-adjust"></i>Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" datatarget="#
navbarSupportedContent" aria-controls="navbarSupportedContent" ariaexpanded="
false" aria-label="Toggle navigation">
            <span class="toggler"><i class="fas fa-bars text-white"></i></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <%= render links %>
            </ul>
        </div>
    </div>
</nav>

app/views/home/partials/_user-card.html.erb
<div class="dev-card p-3 my-3 text-center">
    <% if user.avatar.attached? %>
    <%= image_tag user.avatar %>
    <% else %>
    <img src="assets/avatar5.jpeg" alt="">
    <% end %>

    <h6 class="dev-name text-white">
        <%= user.name %>
        <span class="appearance <%= user.state %>" id="js-appearance<%= user.id
%>">
            <i class="fas fa-circle"></i>
        </span>
    </h6>
    <div class="dev-icons">
        <%= link_to user.github_link, class:'github-icon m-2', title: "Github
page", data: {toggle: "tooltip", placement: "top"} do %>
        <i class="fab fa-github-square"></i>
        <% end %>
        <%= link_to '', class:"camera-icon m-2 #{user.state}", id:"js-camera-icon#
{user.id}", title: "Start a video call with #{user.name}", data: {id: user.id,
name: user.name, toggle: "tooltip", placement: "top"}, remote: true do %>
        <i class="fas fa-video"></i>
        <% end %>
    </div>
</div>

app/views/home/partials/nav/_auth_links.html.erb
<li class="nav-item">
    <%= link_to 'Sign Up', register_path, class: 'nav-link signup-btn btn btnsuccess
py-1 mx-3', data: {turbolinks: false} %>
</li>
<li class="nav-item">
    <%= link_to 'Log In', login_path, class: 'nav-link mx-3' %>
</li>

app/views/home/partials/nav/_dropdown.html.erb
<li class="nav-item">
    <%= render change_state_btn %>
</li>
<li class="nav-item dropdown">
    <a class="nav-link mx-3 dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.name %>
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to 'Logout', logout_path, class: 'dropdown-item', method:
:delete %>
    </div>
</li>

app/views/home/partials/startbtn/_authbtn.html.erb
<%= link_to 'Start now', login_path, class: 'start-btn btn btn-success mr-1', id:
'js-start-btn-auth' %>

app/views/home/partials/startbtn/_scrollbtn.html.erb
<%= link_to 'Start now', '#', class: 'start-btn btn btn-success mr-1', id: 'jsstart-
btn' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>VideoChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?
family=Muli:300,400,500,600,700,800&display=swap" rel="stylesheet">
</head>

<body>


    <!-- Devise notification styled with bootstrap -->
    <% if notice %>
    <div class="notice alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" arialabel="
Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <% elsif alert %>
    <div class="danger alert alert-danger alert-dismissible fade show" role="alert">
        <p><%= alert %></p>
        <button type="button" class="close" data-dismiss="alert" arialabel="
Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <% end %>
    <%= yield %>


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>